(function(b,c){"object"==typeof exports?module.exports=c():"function"==typeof define&&define.amd?define(c):b.Spinner=c()})(this,function(){function b(a,b){var c=document.createElement(a||"div"),d;for(d in b)c[d]=b[d];return c}function c(a){for(var b=1,c=arguments.length;b<c;b++)a.appendChild(arguments[b]);return a}function d(a,b,c,d){var f=["opacity",b,~~(100*a),c,d].join("-");c=.01+c/d*100;d=Math.max(1-(1-a)/b*(100-c),a);var g=m.substring(0,m.indexOf("Animation")).toLowerCase();p[f]||(B.insertRule("@"+
(g&&"-"+g+"-"||"")+"keyframes "+f+"{0%{opacity:"+d+"}"+c+"%{opacity:"+a+"}"+(c+.01)+"%{opacity:1}"+(c+b)%100+"%{opacity:"+a+"}100%{opacity:"+d+"}}",B.cssRules.length),p[f]=1);return f}function a(a,b){var c=a.style,d,f;if(void 0!==c[b])return b;b=b.charAt(0).toUpperCase()+b.slice(1);for(f=0;f<t.length;f++)if(d=t[f]+b,void 0!==c[d])return d}function g(b,c){for(var d in c)b.style[a(b,d)||d]=c[d];return b}function f(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)void 0===a[d]&&
(a[d]=c[d])}return a}function n(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a=a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b}function k(a){if("undefined"==typeof this)return new k(a);this.opts=f(a||{},k.defaults,x)}function l(){function a(C,c){return b("<"+C+' xmlns="urn:schemas-microsoft.com:vml" class="spin-vml">',c)}B.addRule(".spin-vml","behavior:url(#default#VML)");k.prototype.lines=function(b,d){function f(){return g(a("group",{coordsize:k+" "+k,coordorigin:-h+" "+-h}),{width:k,
height:k})}function n(b,v,k){c(m,c(g(f(),{rotation:360/d.lines*b+"deg",left:~~v}),c(g(a("roundrect",{arcsize:d.corners}),{width:h,height:d.width,left:d.radius,top:-d.width>>1,filter:k}),a("fill",{color:d.color,opacity:d.opacity}),a("stroke",{opacity:0}))))}var h=d.length+d.width,k=2*h,l=2*-(d.width+d.length)+"px",m=g(f(),{position:"absolute",top:l,left:l});if(d.shadow)for(l=1;l<=d.lines;l++)n(l,-2,"progid:DXImageTransform.Microsoft.Blur(pixelradius=2,makeshadow=1,shadowopacity=.3)");for(l=1;l<=d.lines;l++)n(l);
return c(b,m)};k.prototype.opacity=function(a,b,C,c){a=a.firstChild;c=c.shadow&&c.lines||0;a&&b+c<a.childNodes.length&&(a=(a=(a=a.childNodes[b+c])&&a.firstChild)&&a.firstChild)&&(a.opacity=C)}}var t=["webkit","Moz","ms","O"],p={},m,B=function(){var a=b("style",{type:"text/css"});c(document.getElementsByTagName("head")[0],a);return a.sheet||a.styleSheet}(),x={lines:12,length:7,width:5,radius:10,rotate:0,corners:1,color:"#000",direction:1,speed:1,trail:100,opacity:.25,fps:20,zIndex:2E9,className:"spinner",
top:"auto",left:"auto",position:"relative"};k.defaults={};f(k.prototype,{spin:function(a){this.stop();var c=this,d=c.opts,f=c.el=g(b(0,{className:d.className}),{position:d.position,width:0,zIndex:d.zIndex}),h=d.radius+d.length+d.width,k,l;a&&(a.insertBefore(f,a.firstChild||null),l=n(a),k=n(f),g(f,{left:("auto"==d.left?l.x-k.x+(a.offsetWidth>>1):parseInt(d.left,10)+h)+"px",top:("auto"==d.top?l.y-k.y+(a.offsetHeight>>1):parseInt(d.top,10)+h)+"px"}));f.setAttribute("role","progressbar");c.lines(f,c.opts);
if(!m){var p=0,t=(d.lines-1)*(1-d.direction)/2,B,w=d.fps,s=w/d.speed,x=(1-d.opacity)/(s*d.trail/100),u=s/d.lines;(function E(){p++;for(var a=0;a<d.lines;a++)B=Math.max(1-(p+(d.lines-a)*u)%s*x,d.opacity),c.opacity(f,a*d.direction+t,B,d);c.timeout=c.el&&setTimeout(E,~~(1E3/w))})()}return c},stop:function(){var a=this.el;a&&(clearTimeout(this.timeout),a.parentNode&&a.parentNode.removeChild(a),this.el=void 0);return this},lines:function(a,v){function f(a,c){return g(b(),{position:"absolute",width:v.length+
v.width+"px",height:v.width+"px",background:a,boxShadow:c,transformOrigin:"left",transform:"rotate("+~~(360/v.lines*k+v.rotate)+"deg) translate("+v.radius+"px,0)",borderRadius:(v.corners*v.width>>1)+"px"})}for(var k=0,h=(v.lines-1)*(1-v.direction)/2,n;k<v.lines;k++)n=g(b(),{position:"absolute",top:1+~(v.width/2)+"px",transform:v.hwaccel?"translate3d(0,0,0)":"",opacity:v.opacity,animation:m&&d(v.opacity,v.trail,h+k*v.direction,v.lines)+" "+1/v.speed+"s linear infinite"}),v.shadow&&c(n,g(f("#000","0 0 4px #000"),
{top:"2px"})),c(a,c(n,f(v.color,"0 0 1px rgba(0,0,0,.1)")));return a},opacity:function(a,b,c){b<a.childNodes.length&&(a.childNodes[b].style.opacity=c)}});var h=g(b("group"),{behavior:"url(#default#VML)"});!a(h,"transform")&&h.adj?l():m=a(h,"animation");return k});
(function(b){if("object"==typeof exports)b(require("jquery"),require("spin"));else if("function"==typeof define&&define.amd)define(["jquery","spin"],b);else{if(!window.Spinner)throw Error("Spin.js not present");b(window.jQuery,window.Spinner)}})(function(b,c){b.fn.spin=function(d,a){return this.each(function(){var g=b(this),f=g.data();f.spinner&&(f.spinner.stop(),delete f.spinner);if(!1!==d){d=b.extend({color:a||g.css("color")},b.fn.spin.presets[d]||d);if("undefined"!==typeof d.right&&"undefined"!==
typeof d.length&&"undefined"!==typeof d.width&&"undefined"!==typeof d.radius){var n=g.css("padding-left"),n="undefined"===typeof n?0:parseInt(n,10);d.left=g.outerWidth()-2*(d.length+d.width+d.radius)-n-d.right;delete d.right}f.spinner=(new c(d)).spin(this)}})};b.fn.spin.presets={tiny:{lines:8,length:2,width:2,radius:3},small:{lines:8,length:4,width:3,radius:5},large:{lines:10,length:8,width:4,radius:8}}});
(function(b){b.fn.spin.presets.wp={trail:60,speed:1.3};b.fn.spin.presets.small=b.extend({lines:8,length:2,width:2,radius:3},b.fn.spin.presets.wp);b.fn.spin.presets.medium=b.extend({lines:8,length:4,width:3,radius:5},b.fn.spin.presets.wp);b.fn.spin.presets.large=b.extend({lines:10,length:6,width:4,radius:7},b.fn.spin.presets.wp);b.fn.spin.presets["small-left"]=b.extend({left:5},b.fn.spin.presets.small);b.fn.spin.presets["small-right"]=b.extend({right:5},b.fn.spin.presets.small);b.fn.spin.presets["medium-left"]=
b.extend({left:5},b.fn.spin.presets.medium);b.fn.spin.presets["medium-right"]=b.extend({right:5},b.fn.spin.presets.medium);b.fn.spin.presets["large-left"]=b.extend({left:5},b.fn.spin.presets.large);b.fn.spin.presets["large-right"]=b.extend({right:5},b.fn.spin.presets.large)})(jQuery);
(function(b){function c(){this.galleries=[];this.findAndSetupNewGalleries()}function d(a){this.gallery=a;this.addCaptionEvents();this.resize();this.gallery.removeClass("tiled-gallery-unresized")}function a(a){function c(){a.resizeAll();d&&f(c)}var d=!1,g=null;b(window).resize(function(){clearTimeout(g);d||f(c);d=!0;g=setTimeout(function(){d=!1},15)})}function g(a){b(window).resize(function(){a.resizeAll()})}c.prototype.findAndSetupNewGalleries=function(){var a=this;b(".tiled-gallery.tiled-gallery-unresized").each(function(){a.galleries.push(new d(b(this)))})};
c.prototype.resizeAll=function(){b.each(this.galleries,function(a,b){b.resize()})};d.prototype.resizeableElementsSelector=".gallery-row, .gallery-group, .tiled-gallery-item img";d.prototype.addCaptionEvents=function(){this.gallery.find(".tiled-gallery-caption").hide();this.gallery.find(".tiled-gallery-item").hover(function(){b(this).find(".tiled-gallery-caption").slideDown("fast")},function(){b(this).find(".tiled-gallery-caption").slideUp("fast")})};d.prototype.getExtraDimension=function(a,b,c){return"horizontal"===
c?(c="border"==b?"borderRightWidth":b+"Right",(parseInt(a.css("border"==b?"borderLeftWidth":b+"Left"),10)||0)+(parseInt(a.css(c),10)||0)):"vertical"===c?(c="border"==b?"borderBottomWidth":b+"Bottom",(parseInt(a.css("border"==b?"borderTopWidth":b+"Top"),10)||0)+(parseInt(a.css(c),10)||0)):0};d.prototype.resize=function(){var a=this.gallery.data("original-width"),c=this.gallery.parent().width(),d=Math.min(1,c/a),f=this;this.gallery.find(this.resizeableElementsSelector).each(function(){var a=b(this),
c=f.getExtraDimension(a,"margin","horizontal"),g=f.getExtraDimension(a,"margin","vertical"),k=f.getExtraDimension(a,"padding","horizontal"),h=f.getExtraDimension(a,"padding","vertical"),C=f.getExtraDimension(a,"border","horizontal"),v=f.getExtraDimension(a,"border","vertical"),k=a.data("original-width")+k+C+c,h=a.data("original-height")+h+v+g;a.width(Math.floor(d*k)-c).height(Math.floor(d*h)-g)})};var f=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;b(document).ready(function(){var d=new c;b("body").on("post-load",function(){d.findAndSetupNewGalleries()});b(document).on("page-rendered.wpcom-newdash",function(){d.findAndSetupNewGalleries()});window.chrome&&f?a(d):g(d)})})(jQuery);
(function(b){function c(){g.setAttribute("content",n);k=!0}function d(a){m=a.accelerationIncludingGravity;l=Math.abs(m.x);t=Math.abs(m.y);p=Math.abs(m.z);b.orientation&&180!==b.orientation||!(7<l||(6<p&&8>t||8>p&&6<t)&&5<l)?k||c():k&&(g.setAttribute("content",f),k=!1)}var a=navigator.userAgent;if(/iPhone|iPad|iPod/.test(navigator.platform)&&/OS [1-5]_[0-9_]* like Mac OS X/i.test(a)&&-1<a.indexOf("AppleWebKit")&&(a=b.document,a.querySelector)){var g=a.querySelector("meta[name=viewport]"),a=g&&g.getAttribute("content"),
f=a+",maximum-scale=1",n=a+",maximum-scale=10",k=!0,l,t,p,m;g&&(b.addEventListener("orientationchange",c,!1),b.addEventListener("devicemotion",d,!1))}})(this);
!function(b){b.flexslider=function(c,d){var a=b(c);a.vars=b.extend({},b.flexslider.defaults,d);var g,f=a.vars.namespace,n=window.navigator&&window.navigator.msPointerEnabled&&window.MSGesture,k=("ontouchstart"in window||n||window.DocumentTouch&&document instanceof DocumentTouch)&&a.vars.touch,l="",t="vertical"===a.vars.direction,p=a.vars.reverse,m=0<a.vars.itemWidth,B="fade"===a.vars.animation,x=""!==a.vars.asNavFor,h={};b.data(c,"flexslider",a);h={init:function(){a.animating=!1;a.currentSlide=parseInt(a.vars.startAt?
a.vars.startAt:0,10);isNaN(a.currentSlide)&&(a.currentSlide=0);a.animatingTo=a.currentSlide;a.atEnd=0===a.currentSlide||a.currentSlide===a.last;a.containerSelector=a.vars.selector.substr(0,a.vars.selector.search(" "));a.slides=b(a.vars.selector,a);a.container=b(a.containerSelector,a);a.count=a.slides.length;a.syncExists=0<b(a.vars.sync).length;"slide"===a.vars.animation&&(a.vars.animation="swing");a.prop=t?"top":"marginLeft";a.args={};a.manualPause=!1;a.stopped=!1;a.started=!1;a.startTimeout=null;
a.transitions=!a.vars.video&&!B&&a.vars.useCSS&&function(){var b=document.createElement("div"),c=["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"],d;for(d in c)if(void 0!==b.style[c[d]])return a.pfx=c[d].replace("Perspective","").toLowerCase(),a.prop="-"+a.pfx+"-transform",!0;return!1}();a.ensureAnimationEnd="";""!==a.vars.controlsContainer&&(a.controlsContainer=0<b(a.vars.controlsContainer).length&&b(a.vars.controlsContainer));""!==a.vars.manualControls&&
(a.manualControls=0<b(a.vars.manualControls).length&&b(a.vars.manualControls));a.vars.randomize&&(a.slides.sort(function(){return Math.round(Math.random())-.5}),a.container.empty().append(a.slides));a.doMath();a.setup("init");a.vars.controlNav&&h.controlNav.setup();a.vars.directionNav&&h.directionNav.setup();a.vars.keyboard&&(1===b(a.containerSelector).length||a.vars.multipleKeyboard)&&b(document).bind("keyup",function(b){b=b.keyCode;a.animating||39!==b&&37!==b||(b=39===b?a.getTarget("next"):37===
b?a.getTarget("prev"):!1,a.flexAnimate(b,a.vars.pauseOnAction))});a.vars.mousewheel&&a.bind("mousewheel",function(b,c){b.preventDefault();var d=0>c?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(d,a.vars.pauseOnAction)});a.vars.pausePlay&&h.pausePlay.setup();a.vars.slideshow&&a.vars.pauseInvisible&&h.pauseInvisible.init();a.vars.slideshow&&(a.vars.pauseOnHover&&a.hover(function(){a.manualPlay||a.manualPause||a.pause()},function(){a.manualPause||a.manualPlay||a.stopped||a.play()}),a.vars.pauseInvisible&&
h.pauseInvisible.isHidden()||(0<a.vars.initDelay?a.startTimeout=setTimeout(a.play,a.vars.initDelay):a.play()));x&&h.asNav.setup();k&&a.vars.touch&&h.touch();(!B||B&&a.vars.smoothHeight)&&b(window).bind("resize orientationchange focus",h.resize);a.find("img").attr("draggable","false");setTimeout(function(){a.vars.start(a)},200)},asNav:{setup:function(){a.asNav=!0;a.animatingTo=Math.floor(a.currentSlide/a.move);a.currentItem=a.currentSlide;a.slides.removeClass(f+"active-slide").eq(a.currentItem).addClass(f+
"active-slide");n?(c._slider=a,a.slides.each(function(){this._gesture=new MSGesture;this._gesture.target=this;this.addEventListener("MSPointerDown",function(a){a.preventDefault();a.currentTarget._gesture&&a.currentTarget._gesture.addPointer(a.pointerId)},!1);this.addEventListener("MSGestureTap",function(c){c.preventDefault();c=b(this);var d=c.index();b(a.vars.asNavFor).data("flexslider").animating||c.hasClass("active")||(a.direction=a.currentItem<d?"next":"prev",a.flexAnimate(d,a.vars.pauseOnAction,
!1,!0,!0))})})):a.slides.on("click touchend MSPointerUp",function(c){c.preventDefault();c=b(this);var d=c.index();0>=c.offset().left-b(a).scrollLeft()&&c.hasClass(f+"active-slide")?a.flexAnimate(a.getTarget("prev"),!0):b(a.vars.asNavFor).data("flexslider").animating||c.hasClass(f+"active-slide")||(a.direction=a.currentItem<d?"next":"prev",a.flexAnimate(d,a.vars.pauseOnAction,!1,!0,!0))})}},controlNav:{setup:function(){a.manualControls?h.controlNav.setupManual():h.controlNav.setupPaging()},setupPaging:function(){var c,
d,g=1;if(a.controlNavScaffold=b('<ol class="'+f+"control-nav "+f+("thumbnails"===a.vars.controlNav?"control-thumbs":"control-paging")+'"></ol>'),1<a.pagingCount)for(var k=0;k<a.pagingCount;k++){if(d=a.slides.eq(k),c="thumbnails"===a.vars.controlNav?'<img src="'+d.attr("data-thumb")+'"/>':"<a>"+g+"</a>","thumbnails"===a.vars.controlNav&&!0===a.vars.thumbCaptions){var n=d.attr("data-thumbcaption");""!=n&&void 0!=n&&(c+='<span class="'+f+'caption">'+n+"</span>")}a.controlNavScaffold.append("<li>"+c+
"</li>");g++}a.controlsContainer?b(a.controlsContainer).append(a.controlNavScaffold):a.append(a.controlNavScaffold);h.controlNav.set();h.controlNav.active();a.controlNavScaffold.delegate("a, img","click touchend MSPointerUp",function(c){if(c.preventDefault(),""===l||l===c.type){var d=b(this),C=a.controlNav.index(d);d.hasClass(f+"active")||(a.direction=C>a.currentSlide?"next":"prev",a.flexAnimate(C,a.vars.pauseOnAction))}""===l&&(l=c.type);h.setToClearWatchedEvent()})},setupManual:function(){a.controlNav=
a.manualControls;h.controlNav.active();a.controlNav.bind("click touchend MSPointerUp",function(c){if(c.preventDefault(),""===l||l===c.type){var d=b(this),g=a.controlNav.index(d);d.hasClass(f+"active")||(a.direction=g>a.currentSlide?"next":"prev",a.flexAnimate(g,a.vars.pauseOnAction))}""===l&&(l=c.type);h.setToClearWatchedEvent()})},set:function(){a.controlNav=b("."+f+"control-nav li "+("thumbnails"===a.vars.controlNav?"img":"a"),a.controlsContainer?a.controlsContainer:a)},active:function(){a.controlNav.removeClass(f+
"active").eq(a.animatingTo).addClass(f+"active")},update:function(c,d){1<a.pagingCount&&"add"===c?a.controlNavScaffold.append(b("<li><a>"+a.count+"</a></li>")):1===a.pagingCount?a.controlNavScaffold.find("li").remove():a.controlNav.eq(d).closest("li").remove();h.controlNav.set();1<a.pagingCount&&a.pagingCount!==a.controlNav.length?a.update(d,c):h.controlNav.active()}},directionNav:{setup:function(){var c=b('<ul class="'+f+'direction-nav"><li><a class="'+f+'prev" href="#">'+a.vars.prevText+'</a></li><li><a class="'+
f+'next" href="#">'+a.vars.nextText+"</a></li></ul>");a.controlsContainer?(b(a.controlsContainer).append(c),a.directionNav=b("."+f+"direction-nav li a",a.controlsContainer)):(a.append(c),a.directionNav=b("."+f+"direction-nav li a",a));h.directionNav.update();a.directionNav.bind("click touchend MSPointerUp",function(c){c.preventDefault();var d;""!==l&&l!==c.type||(d=b(this).hasClass(f+"next")?a.getTarget("next"):a.getTarget("prev"),a.flexAnimate(d,a.vars.pauseOnAction));""===l&&(l=c.type);h.setToClearWatchedEvent()})},
update:function(){var b=f+"disabled";1===a.pagingCount?a.directionNav.addClass(b).attr("tabindex","-1"):a.vars.animationLoop?a.directionNav.removeClass(b).removeAttr("tabindex"):0===a.animatingTo?a.directionNav.removeClass(b).filter("."+f+"prev").addClass(b).attr("tabindex","-1"):a.animatingTo===a.last?a.directionNav.removeClass(b).filter("."+f+"next").addClass(b).attr("tabindex","-1"):a.directionNav.removeClass(b).removeAttr("tabindex")}},pausePlay:{setup:function(){var c=b('<div class="'+f+'pauseplay"><a></a></div>');
a.controlsContainer?(a.controlsContainer.append(c),a.pausePlay=b("."+f+"pauseplay a",a.controlsContainer)):(a.append(c),a.pausePlay=b("."+f+"pauseplay a",a));h.pausePlay.update(a.vars.slideshow?f+"pause":f+"play");a.pausePlay.bind("click touchend MSPointerUp",function(c){c.preventDefault();(""===l||l===c.type)&&(b(this).hasClass(f+"pause")?(a.manualPause=!0,a.manualPlay=!1,a.pause()):(a.manualPause=!1,a.manualPlay=!0,a.play()));""===l&&(l=c.type);h.setToClearWatchedEvent()})},update:function(b){"play"===
b?a.pausePlay.removeClass(f+"pause").addClass(f+"play").html(a.vars.playText):a.pausePlay.removeClass(f+"play").addClass(f+"pause").html(a.vars.pauseText)}},touch:function(){function b(C){a.animating?C.preventDefault():(window.navigator.msPointerEnabled||1===C.touches.length)&&(a.pause(),I=t?a.h:a.w,s=Number(new Date),u=C.touches[0].pageX,J=C.touches[0].pageY,D=m&&p&&a.animatingTo===a.last?0:m&&p?a.limit-(a.itemW+a.vars.itemMargin)*a.move*a.animatingTo:m&&a.currentSlide===a.last?a.limit:m?(a.itemW+
a.vars.itemMargin)*a.move*a.currentSlide:p?(a.last-a.currentSlide+a.cloneOffset)*I:(a.currentSlide+a.cloneOffset)*I,l=t?J:u,x=t?u:J,c.addEventListener("touchmove",d,!1),c.addEventListener("touchend",f,!1))}function d(b){u=b.touches[0].pageX;J=b.touches[0].pageY;w=t?l-J:l-u;F=t?Math.abs(w)<Math.abs(u-x):Math.abs(w)<Math.abs(J-x);(!F||500<Number(new Date)-s)&&(b.preventDefault(),!B&&a.transitions&&(a.vars.animationLoop||(w/=0===a.currentSlide&&0>w||a.currentSlide===a.last&&0<w?Math.abs(w)/I+2:1),a.setProps(D+
w,"setTouch")))}function f(){if(c.removeEventListener("touchmove",d,!1),a.animatingTo===a.currentSlide&&!F&&null!==w){var b=p?-w:w,C=0<b?a.getTarget("next"):a.getTarget("prev");a.canAdvance(C)&&(550>Number(new Date)-s&&50<Math.abs(b)||Math.abs(b)>I/2)?a.flexAnimate(C,a.vars.pauseOnAction):B||a.flexAnimate(a.currentSlide,a.vars.pauseOnAction,!0)}c.removeEventListener("touchend",f,!1);D=w=x=l=null}function g(b){b.stopPropagation();a.animating?b.preventDefault():(a.pause(),c._gesture.addPointer(b.pointerId),
E=0,I=t?a.h:a.w,s=Number(new Date),D=m&&p&&a.animatingTo===a.last?0:m&&p?a.limit-(a.itemW+a.vars.itemMargin)*a.move*a.animatingTo:m&&a.currentSlide===a.last?a.limit:m?(a.itemW+a.vars.itemMargin)*a.move*a.currentSlide:p?(a.last-a.currentSlide+a.cloneOffset)*I:(a.currentSlide+a.cloneOffset)*I)}function h(a){a.stopPropagation();var b=a.target._slider;if(b){var d=-a.translationX,f=-a.translationY;return E+=t?f:d,w=E,F=t?Math.abs(E)<Math.abs(-d):Math.abs(E)<Math.abs(-f),a.detail===a.MSGESTURE_FLAG_INERTIA?
(setImmediate(function(){c._gesture.stop()}),void 0):((!F||500<Number(new Date)-s)&&(a.preventDefault(),!B&&b.transitions&&(b.vars.animationLoop||(w=E/(0===b.currentSlide&&0>E||b.currentSlide===b.last&&0<E?Math.abs(E)/I+2:1)),b.setProps(D+w,"setTouch"))),void 0)}}function k(a){a.stopPropagation();if(a=a.target._slider){if(a.animatingTo===a.currentSlide&&!F&&null!==w){var b=p?-w:w,c=0<b?a.getTarget("next"):a.getTarget("prev");a.canAdvance(c)&&(550>Number(new Date)-s&&50<Math.abs(b)||Math.abs(b)>I/
2)?a.flexAnimate(c,a.vars.pauseOnAction):B||a.flexAnimate(a.currentSlide,a.vars.pauseOnAction,!0)}D=w=x=l=null;E=0}}var l,x,D,I,w,s,F=!1,u=0,J=0,E=0;n?(c.style.msTouchAction="none",c._gesture=new MSGesture,c._gesture.target=c,c.addEventListener("MSPointerDown",g,!1),c._slider=a,c.addEventListener("MSGestureChange",h,!1),c.addEventListener("MSGestureEnd",k,!1)):c.addEventListener("touchstart",b,!1)},resize:function(){!a.animating&&a.is(":visible")&&(m||a.doMath(),B?h.smoothHeight():m?(a.slides.width(a.computedW),
a.update(a.pagingCount),a.setProps()):t?(a.viewport.height(a.h),a.setProps(a.h,"setTotal")):(a.vars.smoothHeight&&h.smoothHeight(),a.newSlides.width(a.computedW),a.setProps(a.computedW,"setTotal")))},smoothHeight:function(b){if(!t||B){var c=B?a:a.viewport;b?c.animate({height:a.slides.eq(a.animatingTo).height()},b):c.height(a.slides.eq(a.animatingTo).height())}},sync:function(c){var d=b(a.vars.sync).data("flexslider"),f=a.animatingTo;switch(c){case "animate":d.flexAnimate(f,a.vars.pauseOnAction,!1,
!0);break;case "play":d.playing||d.asNav||d.play();break;case "pause":d.pause()}},uniqueID:function(a){return a.find("[id]").each(function(){var a=b(this);a.attr("id",a.attr("id")+"_clone")}),a},pauseInvisible:{visProp:null,init:function(){var b=["webkit","moz","ms","o"];if("hidden"in document)return"hidden";for(var c=0;c<b.length;c++)b[c]+"Hidden"in document&&(h.pauseInvisible.visProp=b[c]+"Hidden");h.pauseInvisible.visProp&&(b=h.pauseInvisible.visProp.replace(/[H|h]idden/,"")+"visibilitychange",
document.addEventListener(b,function(){h.pauseInvisible.isHidden()?a.startTimeout?clearTimeout(a.startTimeout):a.pause():a.started?a.play():0<a.vars.initDelay?setTimeout(a.play,a.vars.initDelay):a.play()}))},isHidden:function(){return document[h.pauseInvisible.visProp]||!1}},setToClearWatchedEvent:function(){clearTimeout(g);g=setTimeout(function(){l=""},3E3)}};a.flexAnimate=function(c,d,g,l,n){if(a.vars.animationLoop||c===a.currentSlide||(a.direction=c>a.currentSlide?"next":"prev"),x&&1===a.pagingCount&&
(a.direction=a.currentItem<c?"next":"prev"),!a.animating&&(a.canAdvance(c,n)||g)&&a.is(":visible")){if(x&&l){g=b(a.vars.asNavFor).data("flexslider");if(a.atEnd=0===c||c===a.count-1,g.flexAnimate(c,!0,!1,!0,n),a.direction=a.currentItem<c?"next":"prev",g.direction=a.direction,Math.ceil((c+1)/a.visible)-1===a.currentSlide||0===c)return a.currentItem=c,a.slides.removeClass(f+"active-slide").eq(c).addClass(f+"active-slide"),!1;a.currentItem=c;a.slides.removeClass(f+"active-slide").eq(c).addClass(f+"active-slide");
c=Math.floor(c/a.visible)}if(a.animating=!0,a.animatingTo=c,d&&a.pause(),a.vars.before(a),a.syncExists&&!n&&h.sync("animate"),a.vars.controlNav&&h.controlNav.active(),m||a.slides.removeClass(f+"active-slide").eq(c).addClass(f+"active-slide"),a.atEnd=0===c||c===a.last,a.vars.directionNav&&h.directionNav.update(),c===a.last&&(a.vars.end(a),a.vars.animationLoop||a.pause()),B)k?(a.slides.eq(a.currentSlide).css({opacity:0,zIndex:1}),a.slides.eq(c).css({opacity:1,zIndex:2}),a.wrapup(D)):(a.slides.eq(a.currentSlide).css({zIndex:1}).animate({opacity:0},
a.vars.animationSpeed,a.vars.easing),a.slides.eq(c).css({zIndex:2}).animate({opacity:1},a.vars.animationSpeed,a.vars.easing,a.wrapup));else{var K,H,T,D=t?a.slides.filter(":first").height():a.computedW;m?(K=a.vars.itemMargin,T=(a.itemW+K)*a.move*a.animatingTo,H=T>a.limit&&1!==a.visible?a.limit:T):H=0===a.currentSlide&&c===a.count-1&&a.vars.animationLoop&&"next"!==a.direction?p?(a.count+a.cloneOffset)*D:0:a.currentSlide===a.last&&0===c&&a.vars.animationLoop&&"prev"!==a.direction?p?0:(a.count+1)*D:p?
(a.count-1-c+a.cloneOffset)*D:(c+a.cloneOffset)*D;a.setProps(H,"",a.vars.animationSpeed);a.transitions?(a.vars.animationLoop&&a.atEnd||(a.animating=!1,a.currentSlide=a.animatingTo),a.container.unbind("webkitTransitionEnd transitionend"),a.container.bind("webkitTransitionEnd transitionend",function(){clearTimeout(a.ensureAnimationEnd);a.wrapup(D)}),clearTimeout(a.ensureAnimationEnd),a.ensureAnimationEnd=setTimeout(function(){a.wrapup(D)},a.vars.animationSpeed+100)):a.container.animate(a.args,a.vars.animationSpeed,
a.vars.easing,function(){a.wrapup(D)})}a.vars.smoothHeight&&h.smoothHeight(a.vars.animationSpeed)}};a.wrapup=function(b){B||m||(0===a.currentSlide&&a.animatingTo===a.last&&a.vars.animationLoop?a.setProps(b,"jumpEnd"):a.currentSlide===a.last&&0===a.animatingTo&&a.vars.animationLoop&&a.setProps(b,"jumpStart"));a.animating=!1;a.currentSlide=a.animatingTo;a.vars.after(a)};a.animateSlides=function(){!a.animating&&a.flexAnimate(a.getTarget("next"))};a.pause=function(){clearInterval(a.animatedSlides);a.animatedSlides=
null;a.playing=!1;a.vars.pausePlay&&h.pausePlay.update("play");a.syncExists&&h.sync("pause")};a.play=function(){a.playing&&clearInterval(a.animatedSlides);a.animatedSlides=a.animatedSlides||setInterval(a.animateSlides,a.vars.slideshowSpeed);a.started=a.playing=!0;a.vars.pausePlay&&h.pausePlay.update("pause");a.syncExists&&h.sync("play")};a.stop=function(){a.pause();a.stopped=!0};a.canAdvance=function(b,c){var d=x?a.pagingCount-1:a.last;return c?!0:x&&a.currentItem===a.count-1&&0===b&&"prev"===a.direction?
!0:x&&0===a.currentItem&&b===a.pagingCount-1&&"next"!==a.direction?!1:b!==a.currentSlide||x?a.vars.animationLoop?!0:a.atEnd&&0===a.currentSlide&&b===d&&"next"!==a.direction?!1:a.atEnd&&a.currentSlide===d&&0===b&&"next"===a.direction?!1:!0:!1};a.getTarget=function(b){return a.direction=b,"next"===b?a.currentSlide===a.last?0:a.currentSlide+1:0===a.currentSlide?a.last:a.currentSlide-1};a.setProps=function(b,c,d){var f=function(){var d=b?b:(a.itemW+a.vars.itemMargin)*a.move*a.animatingTo;return-1*function(){if(m)return"setTouch"===
c?b:p&&a.animatingTo===a.last?0:p?a.limit-(a.itemW+a.vars.itemMargin)*a.move*a.animatingTo:a.animatingTo===a.last?a.limit:d;switch(c){case "setTotal":return p?(a.count-1-a.currentSlide+a.cloneOffset)*b:(a.currentSlide+a.cloneOffset)*b;case "setTouch":return b;case "jumpEnd":return p?b:a.count*b;case "jumpStart":return p?a.count*b:b;default:return b}}()+"px"}();a.transitions&&(f=t?"translate3d(0,"+f+",0)":"translate3d("+f+",0,0)",d=void 0!==d?d/1E3+"s":"0s",a.container.css("-"+a.pfx+"-transition-duration",
d),a.container.css("transition-duration",d));a.args[a.prop]=f;(a.transitions||void 0===d)&&a.container.css(a.args);a.container.css("transform",f)};a.setup=function(c){if(B)a.slides.css({width:"100%","float":"left",marginRight:"-100%",position:"relative"}),"init"===c&&(k?a.slides.css({opacity:0,display:"block",webkitTransition:"opacity "+a.vars.animationSpeed/1E3+"s ease",zIndex:1}).eq(a.currentSlide).css({opacity:1,zIndex:2}):a.slides.css({opacity:0,display:"block",zIndex:1}).eq(a.currentSlide).css({zIndex:2}).animate({opacity:1},
a.vars.animationSpeed,a.vars.easing)),a.vars.smoothHeight&&h.smoothHeight();else{var d,g;"init"===c&&(a.viewport=b('<div class="'+f+'viewport"></div>').css({overflow:"hidden",position:"relative"}).appendTo(a).append(a.container),a.cloneCount=0,a.cloneOffset=0,p&&(g=b.makeArray(a.slides).reverse(),a.slides=b(g),a.container.empty().append(a.slides)));a.vars.animationLoop&&!m&&(a.cloneCount=2,a.cloneOffset=1,"init"!==c&&a.container.find(".clone").remove(),h.uniqueID(a.slides.first().clone().addClass("clone").attr("aria-hidden",
"true")).appendTo(a.container),h.uniqueID(a.slides.last().clone().addClass("clone").attr("aria-hidden","true")).prependTo(a.container));a.newSlides=b(a.vars.selector,a);d=p?a.count-1-a.currentSlide+a.cloneOffset:a.currentSlide+a.cloneOffset;t&&!m?(a.container.height(200*(a.count+a.cloneCount)+"%").css("position","absolute").width("100%"),setTimeout(function(){a.newSlides.css({display:"block"});a.doMath();a.viewport.height(a.h);a.setProps(d*a.h,"init")},"init"===c?100:0)):(a.container.width(200*(a.count+
a.cloneCount)+"%"),a.setProps(d*a.computedW,"init"),setTimeout(function(){a.doMath();a.newSlides.css({width:a.computedW,"float":"left",display:"block"});a.vars.smoothHeight&&h.smoothHeight()},"init"===c?100:0))}m||a.slides.removeClass(f+"active-slide").eq(a.currentSlide).addClass(f+"active-slide");a.vars.init(a)};a.doMath=function(){var b=a.slides.first(),c=a.vars.itemMargin,d=a.vars.minItems,f=a.vars.maxItems;a.w=void 0===a.viewport?a.width():a.viewport.width();a.h=b.height();a.boxPadding=b.outerWidth()-
b.width();m?(a.itemT=a.vars.itemWidth+c,a.minW=d?d*a.itemT:a.w,a.maxW=f?f*a.itemT-c:a.w,a.itemW=a.minW>a.w?(a.w-c*(d-1))/d:a.maxW<a.w?(a.w-c*(f-1))/f:a.vars.itemWidth>a.w?a.w:a.vars.itemWidth,a.visible=Math.floor(a.w/a.itemW),a.move=0<a.vars.move&&a.vars.move<a.visible?a.vars.move:a.visible,a.pagingCount=Math.ceil((a.count-a.visible)/a.move+1),a.last=a.pagingCount-1,a.limit=1===a.pagingCount?0:a.vars.itemWidth>a.w?a.itemW*(a.count-1)+c*(a.count-1):(a.itemW+c)*a.count-a.w-c):(a.itemW=a.w,a.pagingCount=
a.count,a.last=a.count-1);a.computedW=a.itemW-a.boxPadding};a.update=function(b,c){a.doMath();m||(b<a.currentSlide?a.currentSlide+=1:b<=a.currentSlide&&0!==b&&(a.currentSlide-=1),a.animatingTo=a.currentSlide);a.vars.controlNav&&!a.manualControls&&("add"===c&&!m||a.pagingCount>a.controlNav.length?h.controlNav.update("add"):("remove"===c&&!m||a.pagingCount<a.controlNav.length)&&(m&&a.currentSlide>a.last&&(a.currentSlide-=1,a.animatingTo-=1),h.controlNav.update("remove",a.last)));a.vars.directionNav&&
h.directionNav.update()};a.addSlide=function(c,d){var f=b(c);a.count+=1;a.last=a.count-1;t&&p?void 0!==d?a.slides.eq(a.count-d).after(f):a.container.prepend(f):void 0!==d?a.slides.eq(d).before(f):a.container.append(f);a.update(d,"add");a.slides=b(a.vars.selector+":not(.clone)",a);a.setup();a.vars.added(a)};a.removeSlide=function(c){var d=isNaN(c)?a.slides.index(b(c)):c;a.count-=1;a.last=a.count-1;isNaN(c)?b(c,a.slides).remove():t&&p?a.slides.eq(a.last).remove():a.slides.eq(c).remove();a.doMath();
a.update(d,"remove");a.slides=b(a.vars.selector+":not(.clone)",a);a.setup();a.vars.removed(a)};h.init()};b(window).blur(function(){focused=!1}).focus(function(){focused=!0});b.flexslider.defaults={namespace:"flex-",selector:".slides > li",animation:"fade",easing:"swing",direction:"horizontal",reverse:!1,animationLoop:!0,smoothHeight:!1,startAt:0,slideshow:!0,slideshowSpeed:7E3,animationSpeed:600,initDelay:0,randomize:!1,thumbCaptions:!1,pauseOnAction:!0,pauseOnHover:!1,pauseInvisible:!0,useCSS:!0,
touch:!0,video:!1,controlNav:!0,directionNav:!0,prevText:"Previous",nextText:"Next",keyboard:!0,multipleKeyboard:!1,mousewheel:!1,pausePlay:!1,pauseText:"Pause",playText:"Play",controlsContainer:"",manualControls:"",sync:"",asNavFor:"",itemWidth:0,itemMargin:0,minItems:1,maxItems:0,move:0,allowOneSlide:!0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){},init:function(){}};b.fn.flexslider=function(c){if(void 0===c&&(c={}),"object"==
typeof c)return this.each(function(){var a=b(this),d=a.find(c.selector?c.selector:".slides > li");1===d.length&&!0===c.allowOneSlide||0===d.length?(d.fadeIn(400),c.start&&c.start(a)):void 0===a.data("flexslider")&&new b.flexslider(this,c)});var d=b(this).data("flexslider");switch(c){case "play":d.play();break;case "pause":d.pause();break;case "stop":d.stop();break;case "next":d.flexAnimate(d.getTarget("next"),!0);break;case "prev":case "previous":d.flexAnimate(d.getTarget("prev"),!0);break;default:"number"==
typeof c&&d.flexAnimate(c,!0)}}}(jQuery);
(function(b){b.fn.fitVids=function(c){var d={customSelector:null};if(!document.getElementById("fit-vids-style")){var a=document.head||document.getElementsByTagName("head")[0],g=document.createElement("div");g.innerHTML='<p>x</p><style id="fit-vids-style">.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>';a.appendChild(g.childNodes[1])}c&&
b.extend(d,c);return this.each(function(){var a="iframe[src*='player.vimeo.com'] iframe[src*='youtube.com'] iframe[src*='youtube-nocookie.com'] iframe[src*='kickstarter.com'][src*='video.html'] object embed".split(" ");d.customSelector&&a.push(d.customSelector);a=b(this).find(a.join(","));a=a.not("object object");a.each(function(){var a=b(this);if(!("embed"===this.tagName.toLowerCase()&&a.parent("object").length||a.parent(".fluid-width-video-wrapper").length)){var c="object"===this.tagName.toLowerCase()||
a.attr("height")&&!isNaN(parseInt(a.attr("height"),10))?parseInt(a.attr("height"),10):a.height(),d=isNaN(parseInt(a.attr("width"),10))?a.width():parseInt(a.attr("width"),10),c=c/d;a.attr("id")||(d="fitvid"+Math.floor(999999*Math.random()),a.attr("id",d));a.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*c+"%");a.removeAttr("height").removeAttr("width")}})})}})(window.jQuery||window.Zepto);
(function(b,c,d){function a(a,d,e){a=c.createElement(a);return d&&(a.id=A+d),e&&(a.style.cssText=e),b(a)}function g(){return d.innerHeight?d.innerHeight:b(d).height()}function f(a,c){c!==Object(c)&&(c={});this.cache={};this.el=a;this.value=function(a){var d;return void 0===this.cache[a]&&(d=b(this.el).attr("data-cbox-"+a),void 0!==d?this.cache[a]=d:void 0!==c[a]?this.cache[a]=c[a]:void 0!==fa[a]&&(this.cache[a]=fa[a])),this.cache[a]};this.get=function(a){a=this.value(a);return b.isFunction(a)?a.call(this.el,
this):a}}function n(a){var b=s.length;a=(G+a)%b;return 0>a?b+a:a}function k(a,b){return Math.round((/%/.test(a)?("x"===b?F.width():g())/100:1)*parseInt(a,10))}function l(a,b){return a.get("photo")||a.get("photoRegex").test(b)}function t(a,b){return a.get("retinaUrl")&&1<d.devicePixelRatio?b.replace(a.get("photoRegex"),a.get("retinaSuffix")):b}function p(a){"contains"in r[0]&&!r[0].contains(a.target)&&a.target!==O[0]&&(a.stopPropagation(),r.focus())}function m(a){m.str!==a&&(r.add(O).removeClass(m.str).addClass(a),
m.str=a)}function B(a){G=0;a&&!1!==a?(s=b("."+V).filter(function(){var c=b.data(this,S);return(new f(this,c)).get("rel")===a}),G=s.index(e.el),-1===G&&(s=s.add(e.el),G=s.length-1)):s=b(e.el)}function x(a){b(c).trigger(a);L.triggerHandler(a)}function h(d){var g;if(!X){if(g=b(d).data("colorbox"),e=new f(d,g),B(e.get("rel")),!P){P=Y=!0;m(e.get("className"));r.css({visibility:"hidden",display:"block",opacity:""});u=a(y,"LoadedContent","width:0; height:0; overflow:hidden; visibility:hidden");H.css({width:"",
height:""}).append(u);M=T.height()+w.height()+H.outerHeight(!0)-H.height();N=D.width()+I.width()+H.outerWidth(!0)-H.width();Q=u.outerHeight(!0);R=u.outerWidth(!0);d=k(e.get("initialWidth"),"x");g=k(e.get("initialHeight"),"y");var h=e.get("maxWidth"),l=e.get("maxHeight");e.w=(!1!==h?Math.min(d,k(h,"x")):d)-R-N;e.h=(!1!==l?Math.min(g,k(l,"y")):g)-Q-M;u.css({width:"",height:e.h});z.position();x(oa);e.get("onOpen");ga.add(da).hide();r.focus();e.get("trapFocus")&&c.addEventListener&&(c.addEventListener("focus",
p,!0),L.one(ha,function(){c.removeEventListener("focus",p,!0)}));e.get("returnFocus")&&L.one(ha,function(){b(e.el).focus()})}O.css({opacity:parseFloat(e.get("opacity"))||"",cursor:e.get("overlayClose")?"pointer":"",visibility:"visible"}).show();e.get("closeButton")?$.html(e.get("close")).appendTo(H):$.appendTo("<div/>");na()}}function C(){!r&&c.body&&(ia=!1,F=b(d),r=a(y).attr({id:S,"class":!1===b.support.opacity?A+"IE":"",role:"dialog",tabindex:"-1"}).hide(),O=a(y,"Overlay").hide(),E=b([a(y,"LoadingOverlay")[0],
a(y,"LoadingGraphic")[0]]),K=a(y,"Wrapper"),H=a(y,"Content").append(da=a(y,"Title"),ea=a(y,"Current"),Z=b('<button type="button"/>').attr({id:A+"Previous"}),W=b('<button type="button"/>').attr({id:A+"Next"}),U=a("button","Slideshow"),E),$=b('<button type="button"/>').attr({id:A+"Close"}),K.append(a(y).append(a(y,"TopLeft"),T=a(y,"TopCenter"),a(y,"TopRight")),a(y,!1,"clear:left").append(D=a(y,"MiddleLeft"),H,I=a(y,"MiddleRight")),a(y,!1,"clear:left").append(a(y,"BottomLeft"),w=a(y,"BottomCenter"),
a(y,"BottomRight"))).find("div div").css({"float":"left"}),J=a(y,!1,"position:absolute; width:9999px; visibility:hidden; display:none; max-width:none;"),ga=W.add(Z).add(ea).add(U),b(c.body).append(O,r.append(K,J)))}function v(){function a(b){1<b.which||b.shiftKey||b.altKey||b.metaKey||b.ctrlKey||(b.preventDefault(),h(this))}return r?(ia||(ia=!0,W.click(function(){z.next()}),Z.click(function(){z.prev()}),$.click(function(){z.close()}),O.click(function(){e.get("overlayClose")&&z.close()}),b(c).bind("keydown."+
A,function(a){var b=a.keyCode;P&&e.get("escKey")&&27===b&&(a.preventDefault(),z.close());P&&e.get("arrowKey")&&s[1]&&!a.altKey&&(37===b?(a.preventDefault(),Z.click()):39===b&&(a.preventDefault(),W.click()))}),b.isFunction(b.fn.on)?b(c).on("click."+A,"."+V,a):b("."+V).live("click."+A,a)),!0):!1}function na(){var c,f,g,h=z.prep,m=++ja;if(Y=!0,q=!1,x(aa),x(ba),e.get("onLoad"),e.h=e.get("height")?k(e.get("height"),"y")-Q-M:e.get("innerHeight")&&k(e.get("innerHeight"),"y"),e.w=e.get("width")?k(e.get("width"),
"x")-R-N:e.get("innerWidth")&&k(e.get("innerWidth"),"x"),e.mw=e.w,e.mh=e.h,e.get("maxWidth")&&(e.mw=k(e.get("maxWidth"),"x")-R-N,e.mw=e.w&&e.w<e.mw?e.w:e.mw),e.get("maxHeight")&&(e.mh=k(e.get("maxHeight"),"y")-Q-M,e.mh=e.h&&e.h<e.mh?e.h:e.mh),c=e.get("href"),la=setTimeout(function(){E.show()},100),e.get("inline")){var n=b(c);g=b("<div>").hide().insertBefore(n);L.one(aa,function(){g.replaceWith(n)});h(n)}else e.get("iframe")?h(" "):e.get("html")?h(e.get("html")):l(e,c)?(c=t(e,c),q=new Image,b(q).addClass(A+
"Photo").bind("error",function(){h(a(y,"Error").html(e.get("imgError")))}).one("load",function(){m===ja&&setTimeout(function(){var a;b.each(["alt","longdesc","aria-describedby"],function(a,c){var d=b(e.el).attr(c)||b(e.el).attr("data-"+c);d&&q.setAttribute(c,d)});e.get("retinaImage")&&1<d.devicePixelRatio&&(q.height/=d.devicePixelRatio,q.width/=d.devicePixelRatio);e.get("scalePhotos")&&(f=function(){q.height-=q.height*a;q.width-=q.width*a},e.mw&&q.width>e.mw&&(a=(q.width-e.mw)/q.width,f()),e.mh&&
q.height>e.mh&&(a=(q.height-e.mh)/q.height,f()));e.h&&(q.style.marginTop=Math.max(e.mh-q.height,0)/2+"px");s[1]&&(e.get("loop")||s[G+1])&&(q.style.cursor="pointer",q.onclick=function(){z.next()});q.style.width=q.width+"px";q.style.height=q.height+"px";h(q)},1)}),q.src=c):c&&J.load(c,e.get("data"),function(c,d){m===ja&&h("error"===d?a(y,"Error").html(e.get("xhrError")):b(this).contents())})}var O,r,K,H,T,D,I,w,s,F,u,J,E,da,ea,U,W,Z,$,ga,e,M,N,Q,R,G,q,P,Y,X,la,z,ia,fa={html:!1,photo:!1,iframe:!1,inline:!1,
transition:"elastic",speed:300,fadeOut:300,width:!1,initialWidth:"600",innerWidth:!1,maxWidth:!1,height:!1,initialHeight:"450",innerHeight:!1,maxHeight:!1,scalePhotos:!0,scrolling:!0,opacity:.9,preloading:!0,className:!1,overlayClose:!0,escKey:!0,arrowKey:!0,top:!1,bottom:!1,left:!1,right:!1,fixed:!1,data:void 0,closeButton:!0,fastIframe:!0,open:!1,reposition:!0,loop:!0,slideshow:!1,slideshowAuto:!0,slideshowSpeed:2500,slideshowStart:"start slideshow",slideshowStop:"stop slideshow",photoRegex:/\.(gif|png|jp(e|g|eg)|bmp|ico|webp|jxr|svg)((#|\?).*)?$/i,
retinaImage:!1,retinaUrl:!1,retinaSuffix:"@2x.$1",current:"image {current} of {total}",previous:"previous",next:"next",close:"close",xhrError:"This content failed to load.",imgError:"This image failed to load.",returnFocus:!0,trapFocus:!0,onOpen:!1,onLoad:!1,onComplete:!1,onCleanup:!1,onClosed:!1,rel:function(){return this.rel},href:function(){return b(this).attr("href")},title:function(){return this.title}},S="colorbox",A="cbox",V=A+"Element",oa=A+"_open",ba=A+"_load",ca=A+"_complete",ka=A+"_cleanup",
ha=A+"_closed",aa=A+"_purge",L=b("<a/>"),y="div",ja=0,ma={},pa=function(){function a(){clearTimeout(h)}function b(){(e.get("loop")||s[G+1])&&(a(),h=setTimeout(z.next,e.get("slideshowSpeed")))}function c(){U.html(e.get("slideshowStop")).unbind(l).one(l,d);L.bind(ca,b).bind(ba,a);r.removeClass(k+"off").addClass(k+"on")}function d(){a();L.unbind(ca,b).unbind(ba,a);U.html(e.get("slideshowStart")).unbind(l).one(l,function(){z.next();c()});r.removeClass(k+"on").addClass(k+"off")}function f(){g=!1;U.hide();
a();L.unbind(ca,b).unbind(ba,a);r.removeClass(k+"off "+k+"on")}var g,h,k=A+"Slideshow_",l="click."+A;return function(){g?e.get("slideshow")||(L.unbind(ka,f),f()):e.get("slideshow")&&s[1]&&(g=!0,L.one(ka,f),e.get("slideshowAuto")?c():d(),U.show())}}();b.colorbox||(b(C),z=b.fn[S]=b[S]=function(a,c){var d,e=this;if(a=a||{},b.isFunction(e))e=b("<a/>"),a.open=!0;else if(!e[0])return e;return e[0]?(C(),v()&&(c&&(a.onComplete=c),e.each(function(){var c=b.data(this,S)||{};b.data(this,S,b.extend(c,a))}).addClass(V),
d=new f(e[0],a),d.get("open")&&h(e[0])),e):e},z.position=function(a,c){function d(){T[0].style.width=w[0].style.width=H[0].style.width=parseInt(r[0].style.width,10)-N+"px";H[0].style.height=D[0].style.height=I[0].style.height=parseInt(r[0].style.height,10)-M+"px"}var f,h,l,m=0,n=0,p=r.offset();if(F.unbind("resize."+A),r.css({top:-9E4,left:-9E4}),h=F.scrollTop(),l=F.scrollLeft(),e.get("fixed")?(p.top-=h,p.left-=l,r.css({position:"fixed"})):(m=h,n=l,r.css({position:"absolute"})),n+=!1!==e.get("right")?
Math.max(F.width()-e.w-R-N-k(e.get("right"),"x"),0):!1!==e.get("left")?k(e.get("left"),"x"):Math.round(Math.max(F.width()-e.w-R-N,0)/2),m+=!1!==e.get("bottom")?Math.max(g()-e.h-Q-M-k(e.get("bottom"),"y"),0):!1!==e.get("top")?k(e.get("top"),"y"):Math.round(Math.max(g()-e.h-Q-M,0)/2),r.css({top:p.top,left:p.left,visibility:"visible"}),K[0].style.width=K[0].style.height="9999px",f={width:e.w+R+N,height:e.h+Q+M,top:m,left:n},a){var q=0;b.each(f,function(b){return f[b]!==ma[b]?(q=a,void 0):void 0});a=
q}ma=f;a||r.css(f);r.dequeue().animate(f,{duration:a||0,complete:function(){d();Y=!1;K[0].style.width=e.w+R+N+"px";K[0].style.height=e.h+Q+M+"px";e.get("reposition")&&setTimeout(function(){F.bind("resize."+A,z.position)},1);c&&c()},step:d})},z.resize=function(a){var b;P&&(a=a||{},a.width&&(e.w=k(a.width,"x")-R-N),a.innerWidth&&(e.w=k(a.innerWidth,"x")),u.css({width:e.w}),a.height&&(e.h=k(a.height,"y")-Q-M),a.innerHeight&&(e.h=k(a.innerHeight,"y")),a.innerHeight||a.height||(b=u.scrollTop(),u.css({height:"auto"}),
e.h=u.height()),u.css({height:e.h}),b&&u.scrollTop(b),z.position("none"===e.get("transition")?0:e.get("speed")))},z.prep=function(d){if(P){var g,h="none"===e.get("transition")?0:e.get("speed");u.remove();u=a(y,"LoadedContent").append(d);u.hide().appendTo(J.show()).css({width:(e.w=e.w||u.width(),e.w=e.mw&&e.mw<e.w?e.mw:e.w,e.w),overflow:e.get("scrolling")?"auto":"hidden"}).css({height:(e.h=e.h||u.height(),e.h=e.mh&&e.mh<e.h?e.mh:e.h,e.h)}).prependTo(H);J.hide();b(q).css({"float":"none"});m(e.get("className"));
g=function(){function a(){!1===b.support.opacity&&r[0].style.removeAttribute("filter")}var d,g,k=s.length;P&&(g=function(){clearTimeout(la);E.hide();x(ca);e.get("onComplete")},da.html(e.get("title")).show(),u.show(),1<k?("string"==typeof e.get("current")&&ea.html(e.get("current").replace("{current}",G+1).replace("{total}",k)).show(),W[e.get("loop")||k-1>G?"show":"hide"]().html(e.get("next")),Z[e.get("loop")||G?"show":"hide"]().html(e.get("previous")),pa(),e.get("preloading")&&b.each([n(-1),n(1)],
function(){var a,d=s[this],d=new f(d,b.data(d,S)),e=d.get("href");e&&l(d,e)&&(e=t(d,e),a=c.createElement("img"),a.src=e)})):ga.hide(),e.get("iframe")?(d=c.createElement("iframe"),"frameBorder"in d&&(d.frameBorder=0),"allowTransparency"in d&&(d.allowTransparency="true"),e.get("scrolling")||(d.scrolling="no"),b(d).attr({src:e.get("href"),name:(new Date).getTime(),"class":A+"Iframe",allowFullScreen:!0}).one("load",g).appendTo(u),L.one(aa,function(){d.src="//about:blank"}),e.get("fastIframe")&&b(d).trigger("load")):
g(),"fade"===e.get("transition")?r.fadeTo(h,1,a):a())};"fade"===e.get("transition")?r.fadeTo(h,0,function(){z.position(0,g)}):z.position(h,g)}},z.next=function(){!Y&&s[1]&&(e.get("loop")||s[G+1])&&(G=n(1),h(s[G]))},z.prev=function(){!Y&&s[1]&&(e.get("loop")||G)&&(G=n(-1),h(s[G]))},z.close=function(){P&&!X&&(X=!0,P=!1,x(ka),e.get("onCleanup"),F.unbind("."+A),O.fadeTo(e.get("fadeOut")||0,0),r.stop().fadeTo(e.get("fadeOut")||0,0,function(){r.hide();O.hide();x(aa);u.remove();setTimeout(function(){X=!1;
x(ha);e.get("onClosed")},1)}))},z.remove=function(){r&&(r.stop(),b.colorbox.close(),r.stop().remove(),O.remove(),X=!1,r=null,b("."+V).removeData(S).removeClass(V),b(c).unbind("click."+A))},z.element=function(){return b(e.el)},z.settings=fa)})(jQuery,document,window);var TINY={};function tid(b){return document.getElementById(b)}function tag(b,c){c=c||document;return c.getElementsByTagName(b)}
TINY.slideshow=function(b){this.infoSpeed=this.imgSpeed=this.speed=10;this.thumbOpacity=this.navHover=70;this.navOpacity=25;this.scrollSpeed=5;this.letterbox="#000";this.n=b;this.c=0;this.a=[]};
TINY.slideshow.prototype={init:function(b,c,d,a,g){b=tid(b);b=tag("li",b);var f=0,n=0;this.l=b.length;this.q=tid(g);this.f=tid(c);this.r=tid(this.info);this.o=parseInt(TINY.style.val(c,"width"));this.thumbs&&(c=tid(this.left),g=tid(this.right),c.onmouseover=new Function('TINY.scroll.init("'+this.thumbs+'",-1,'+this.scrollSpeed+")"),c.onmouseout=g.onmouseout=new Function('TINY.scroll.cl("'+this.thumbs+'")'),g.onmouseover=new Function('TINY.scroll.init("'+this.thumbs+'",1,'+this.scrollSpeed+")"),this.p=
tid(this.thumbs));for(f;f<this.l;f++)this.a[f]={},c=b[f],g=this.a[f],g.t=tag("h3",c)[0].innerHTML,g.io=tag("h3",c)[0].style.opacity,g.d=tag("p",c)[0].innerHTML,g.l=tag("a",c)[0]?tag("a",c)[0].href:"",g.tg=""!=tag("a",c)[0]?tag("a",c)[0].target:"_self",g.p=tag("span",c)[0].innerHTML,this.thumbs&&(c=tag("img",c)[0],this.p.appendChild(c),n+=parseInt(c.offsetWidth),f!=this.l-1&&(c.style.marginRight=this.spacing+"px",n+=this.spacing),this.p.style.width=n+"px",c.style.opacity=this.thumbOpacity/100,c.style.filter=
"alpha(opacity="+this.thumbOpacity+")",c.onmouseover=new Function("TINY.alpha.set(this,100,5)"),c.onmouseout=new Function("TINY.alpha.set(this,"+this.thumbOpacity+",5)"),c.onclick=new Function(this.n+".pr("+f+",1)"));d&&a&&(d=tid(d),a=tid(a),d.style.opacity=a.style.opacity=this.navOpacity/100,d.style.filter=a.style.filter="alpha(opacity="+this.navOpacity+")",d.onmouseover=a.onmouseover=new Function("TINY.alpha.set(this,"+this.navHover+",5)"),d.onmouseout=a.onmouseout=new Function("TINY.alpha.set(this,"+
this.navOpacity+",5)"),d.onclick=new Function(this.n+".mv(-1,1)"),a.onclick=new Function(this.n+".mv(1,1)"));this.auto?this.is(0,0):this.is(0,1)},mv:function(b,c){var d=this.c+b;this.c=d=0>d?this.l-1:d>this.l-1?0:d;this.pr(d,c)},pr:function(b,c){clearTimeout(this.lt);c&&clearTimeout(this.at);this.c=b;this.is(b,c)},is:function(b,c){this.info&&(0<this.a[b].t.length||0<this.a[b].d.length?TINY.height.set(this.r,1,this.infoSpeed/2,-1):TINY.height.set(this.r,0,this.infoSpeed/2,-1));var d=new Image;d.style.opacity=
0;d.style.filter="alpha(opacity=0)";this.i=d;d.onload=new Function(this.n+".le("+b+","+c+")");string=this.a[b].p;string=string.replace(/&amp;/g,"&");d.src=string;if(this.thumbs){var d=tag("img",this.p),a=d.length,g=0;for(g;g<a;g++)d[g].style.borderColor=g!=b?"":this.active}},le:function(b,c){this.f.appendChild(this.i);parseInt(this.i.offsetWidth);TINY.alpha.set(this.i,100,this.imgSpeed);var d=new Function(this.n+".nf("+b+")");this.lt=setTimeout(d,100*this.imgSpeed);if(!c||!0==this.auto&&!0==this.alwaysauto)this.at=
setTimeout(new Function(this.n+".mv(1,0)"),1E3*this.speed);""!=this.a[b].l?(d=this.a[b].l.toLowerCase().match(/\.jpg$|\.jpeg$|\.png$|\.gif$|\.bmp$/),this.q.onclick="true"!=this.imagesthickbox||".jpg"!=d&&".jpeg"!=d&&".png"!=d&&".gif"!=d&&".bmp"!=d?new Function('window.open("'+this.a[b].l+'","'+this.a[b].tg+'")'):new Function('jQuery.colorbox({href:"'+this.a[b].l+'",maxWidth:"90%",maxHeight:"90%",title:"'+this.a[b].t+'"})'),this.q.onmouseover=new Function('this.className="'+this.linkclass+'"'),this.q.onmouseout=
new Function('this.className=""'),this.q.style.cursor="pointer"):(this.q.onclick=this.q.onmouseover=null,this.q.style.cursor="default");d=tag("img",this.f);2<=d.length&&this.f.removeChild(d[0])},nf:function(b){if(this.info){b=this.a[b];tag("h3",this.r)[0].innerHTML=b.t;tag("p",this.r)[0].innerHTML=b.d;this.r.style.height="auto";var c=parseInt(this.r.offsetHeight);this.r.style.height=0;if(0<b.t.length||0<b.d.length)TINY.height.set(this.r,c,this.infoSpeed,0),TINY.alpha.set(this.r,b.io,5)}}};
TINY.scroll=function(){return{init:function(b,c,d){b="object"==typeof b?b:tid(b);var a=b.style.left||TINY.style.val(b,"left");b.style.left=a;var g=1==c?Math.abs(parseInt(b.offsetWidth)-parseInt(b.parentNode.offsetWidth)):0;(b.childNodes.length+1)*b.firstChild.width>b.parentNode.offsetWidth&&(b.si=setInterval(function(){TINY.scroll.mv(b,g,c,d)},20))},mv:function(b,c,d,a){var g=parseInt(b.style.left);g==c?TINY.scroll.cl(b):(c=Math.abs(c+g),b.style.left=g-(c<a?c:a)*d+"px")},cl:function(b){b="object"==
typeof b?b:tid(b);clearInterval(b.si)}}}();TINY.height=function(){return{set:function(b,c,d,a){b="object"==typeof b?b:tid(b);a=b.offsetHeight;var g=b.style.height||TINY.style.val(b,"height"),g=a-parseInt(g),f=a-g>c?-1:1;clearInterval(b.si);b.si=setInterval(function(){TINY.height.tw(b,c,g,f,d)},20)},tw:function(b,c,d,a,g){d=b.offsetHeight-d;d==c?clearInterval(b.si):d!=c&&(b.style.height=d+Math.ceil(Math.abs(c-d)/g)*a+"px")}}}();
TINY.alpha=function(){return{set:function(b,c,d){b="object"==typeof b?b:tid(b);var a=b.style.opacity||TINY.style.val(b,"opacity"),g=c>100*a?1:-1;b.style.opacity=a;clearInterval(b.ai);b.ai=setInterval(function(){TINY.alpha.tw(b,c,g,d)},20)},tw:function(b,c,d,a){var g=Math.round(100*b.style.opacity);g==c?clearInterval(b.ai):(c=g+Math.ceil(Math.abs(c-g)/a)*d,b.style.opacity=c/100,b.style.filter="alpha(opacity="+c+")")}}}();
TINY.style=function(){return{val:function(b,c){b="object"==typeof b?b:tid(b);return b.currentStyle?b.currentStyle[c]:document.defaultView.getComputedStyle(b,null).getPropertyValue(c)}}}();